### ISSUE TITLE
Are there issues with many related samples?

### ISSUE THREAD

**Issue by holtgrewe** [tfwillems/HipSTR#11]
I have a cohort with ~75 individuals where I would like to genotype STRs. The data consists mostly of trios and quatros. Thus, the genotypes seen in the data are not independent. Is this a problem for HipSTR?

**Comment by tfwillems** [comment]
We haven't explicitly tested the affect of including related samples. The only place where I think this may have a negative effect is when we're calculating a noise model for each STR locus. But if your 75 samples consists of trios or quads, this should have a relatively minor effect. For the genotyping, I think including the related samples will actually slightly improve genotyping accuracy, as it will make it easier to identify candidate STR haplotypes.
