### ISSUE TITLE
Obtaining TRF BED File

### ISSUE THREAD

**Issue by holtgrewe** [tfwillems/HipSTR#12]
Hi, where can I obtain the TRF BED file that I need for running HipSTR?

**Comment by holtgrewe** [comment]
I'm just taking the lobSTR one for now.

**Comment by tfwillems** [comment]
We're working on preparing a final reference file. In the mean time, the lobSTR file is a good alternative, but there will be some slight reduction in accuracy. For the Y-chromosome, you can find a finalized reference file here: https://github.com/tfwillems/ystr-mut-rates
