### ISSUE TITLE
--quiet option ?

### ISSUE THREAD

**Issue by brentp** [tfwillems/HipSTR#23]
It looks like there are about 30 lines of logging per STR. It would be nice if there were a --quiet option. I can use `--log`, but it's still too many messages to make sense of.

(BTW, thanks for the well-documented, easy to install, and easy to run tool)

**Comment by tfwillems** [comment]
Absolutely Brent! Definitely agree that the logging can get cumbersome and discarding all of these messages would be a useful option to have. I'll hopefully integrate a fix in the next few days or so, as the required changes should be pretty minimal

**Comment by tfwillems** [comment]
A --quiet option has been added in commit e5034baf672b46ac9dcd69bfc7b177921d25082e

**Comment by brentp** [comment]
thank you. 

an unrelated question. The help lists a few scenarios of usage for cohort-size::depth combinations. What would be the recommended way to run with hundreds of 30X samples? Should I just run them all together and parallelize by chunks of  `--regions` or should I limit to groups of $n samples?

**Comment by shukwong** [comment]
I ran mine with 90 samples per batch and that worked pretty well, but I would like to hear whether there is a better option.

**Comment by tfwillems** [comment]
On the STR side, I definitely recommend parallelizing by chunks of regions if you have extra CPUs/nodes to spare.

On the sample side, theoretically you should be able to run all samples concurrently in a single run. We've done up to 200 30x genomes in a batch but have never really tried above that. In practice, disk IO might become a bit of an issue if you have much more than 200 30x genomes. This has been my limited experience in a handful of instances, but would definitely be interested if you encounter the same problem on your end.

I'd suggest doing a test run on maybe the first 10000 STRs in your reference using i) all of your samples concurrently and 2) in batches of 200 samples. If it seems like the runtime for all samples concurrently is roughly the same or faster than the sum of the batches (which it should be if IO isn't an issue), I'd definitely opt for 1. If option 1 is much longer, it likely means that IO is the issue and option 2 is probably best. It'd be great if you could let me know what your experience is!
