### ISSUE TITLE
handle errors from htslib

### ISSUE THREAD

**Issue by brentp** [tfwillems/HipSTR#25]
htslib returns errors as < -1 and EOF as -1 for a lot of its API. I am running HipSTR on AWS and occasionally see network problems leading to `HipSTR` outputting a lot of lines of:
``` 
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
```
without exiting. 
I believe a change like this:
```Diff
diff --git a/src/bam_io.cpp b/src/bam_io.cpp
index 7064998..60f38d3 100644
--- a/src/bam_io.cpp
+++ b/src/bam_io.cpp
@@ -90,10 +90,14 @@ bool BamCramReader::SetRegion(const std::string& chrom, int32_t start, int32_t e
 
 bool BamCramReader::GetNextAlignment(BamAlignment& aln){
   if (iter_ == NULL) return false;
+  int ret;
 
-  if (sam_itr_next(in_, iter_, aln.b_) < 0){
+  if (ret = sam_itr_next(in_, iter_, aln.b_) < 0){
     hts_itr_destroy(iter_);
     iter_ = NULL;
+    if (ret < -1){
+        // Handle error
+    }
     return false;
   }
 
```

is the starting point, but it might require that the return from `GetNextAlignment` is an int rather than bool.

**Comment by tfwillems** [comment]
Unfortunately I think sam_itr_next also returns -1 if there are no more alignments in the current region of interest. As a result, distinguishing between finishing a region and an htslib IO issue may be a bit more complicated.

In the cases you've encountered, are these issues due to BAM files that didn't download completely? Would the ideal behavior be that HipSTR aborts when encountering these issues or continues chugging along but suppresses the htslib errors?

**Comment by brentp** [comment]
yes, -1 is a valid EOF-like, less than -1 is an error.

This happens when I mount S3 as a file system and some network error (or bug in the software that makes S3 look like a file system) results in a read error.

**Comment by brentp** [comment]
Ideal behavior would be to exit with non-zero value.

**Comment by tfwillems** [comment]
I'm not very familiar with the htslib internals, but it seems like **bgzf_seek()** errors won't be captured by this. Failed calls to **bgzf_seek()** in turn cause **hts_itr_next()** to return -1. Would you expect the IO errors you're encountering to fail at the **bgzf_seek()** stage or when invoking **readrec** inside of **hts_itr_next()**?

**Comment by brentp** [comment]
well, I would guess that `readrec` would fail if the seek didn't work, so I think that handling the return of < -1 from `hts_itr_next` should be sufficient.
