### ISSUE TITLE
Question: can HipSTR output confident reference calls?

### ISSUE THREAD

**Issue by nh13** [tfwillems/HipSTR#28]
If the samples HipStr is joint calling all match the reference, is a variant record/line outputted.  In many cases, it is important not only to see the variant sites, but also evidence for non-variant sites (think gVCFs).

**Comment by tfwillems** [comment]
Yes. If HipSTR genotypes an STR and no variants are detected across any of the samples, it'll automatically output a VCF record with no alternate alleles in which all samples have a 0/0 genotype.
