### ISSUE TITLE
Genotype FORMAT tags should have a proper type

### ISSUE THREAD

**Issue by nh13** [tfwillems/HipSTR#31]
For example, the `GB` tag has type `String` whereas it would be better if it had type `.` (unbounded), or `R`/`A` where appropriate.  Similarly for other tags.  This would allow downstream users to expect a value per genotype or per allele.

**Comment by tfwillems** [comment]
I'm not sure I agree with this. The structure of the `GB` field exactly mirrors that of the `GT` field. As the `GT` field has a `String` type, I feel it's more natural for `GB` to do so as well. `GB` is always structured as `NUM1|NUM2`. Unbounded seems a bit unnatural, as we know the exact structure of `GB`. `R` and `A` are also not applicable, as they correspond to having one value for all alleles or all alternate alleles, respectively, whereas `GB` always has two values (except for haploid genotypes). 

As` PSNP` and `PDP`are structured in analogous ways, I also think their types are correctly specified as `String`. 

The most questionable types are likely for `ALLREADS` and `MALLREADS`. However, given that these are structured in the format `KEY1|COUNT1;KEY2|COUNT2`, `String` again seems like the appropriate type. 

That being said, I'm happy to modify some types if you have counter examples

**Comment by nh13** [comment]
The comment I would make would be that there a few libraries that leverage the type to return a list of values rather than just the string, with the latter leaving it to the user to parse the field.  Happy for it to be either way.  I agree that it's odd there isn't a type saying the same # of values as the ploidy of the genotype.  For what it's worth, I am forcing haploid calls in my application.

**Comment by tfwillems** [comment]
Agreed, a ploidy-related count would definitely be the most natural. Fingers crossed for VCF V4.4 ...

For now I think I'll leave it as is. I'm definitely in favor of facilitating downstream parsing, but I think the added complexity and the loss of phasing information make me hesitant to alter the FORMAT types

**Comment by brentp** [comment]
`Number=G` 
No?

**Comment by tfwillems** [comment]
@brentp 
I believe `G` corresponds to the number of unphased genotypes, not 2 for diploid genotypes and 1 for haploid genotypes as we'd desire for `GB`
