### ISSUE TITLE
HipSTR uses bases from overlapping read pairs

### ISSUE THREAD

**Issue by nh13** [tfwillems/HipSTR#34]
If we have overlapping read pairs, overlapping bases are being double-counted in the genotype's "DP" (depth) calculation, and possibly when genotyping.  Prior to HipSTR, we can certainly use tools like [ClipBam](http://fulcrumgenomics.github.io/fgbio/tools/latest/ClipBam.html) to clip overlapping reads, or extend the tool to do so more intelligently (keep the end that overlaps the region fully).

**Comment by tfwillems** [comment]
Thanks for reporting this bug @nh13. The *DP* field does indeed double count overlapping mate pairs. However, during genotyping, we accurately model overlapping mate pairs as coming from the same DNA molecule. As a result, the genotype likelihoods and the entire genotyping procedure are correct and unaffected. I would therefore strongly advise against clipping the reads.

I'll go ahead and fix the DP double counting issue
