### ISSUE TITLE
Best way to debug when the stutter model fails to train?

### ISSUE THREAD

**Issue by nh13** [tfwillems/HipSTR#35]
Here's the output of HipSTR.
```
Processing region 1 230905361 230905429
59000 reads overlapped region, of which
    0 were hard clipped
    54 had an 'N' base call
    738 had low base quality scores
    0 did not span the STR
    8 did not have a unique mapping
    110 did not have a mate pair
    58090 PASSED ALL FILTERS
Found 58090 fully paired reads and 0 unpaired reads for downstream analyses
Phased SNPs add info for 0 out of 58090 reads and 0 out of 659 samples
Building EM stutter model
Training EM stutter model
Stutter model training failed for locus 1:230905361-230905429 with 10024 informative reads
Locus timing:
 BAM seek time       = 0.000343 seconds
 Read filtering      = 4.20388 seconds
 SNP info extraction = 0.121632 seconds
 Stutter estimation  = 48.3759 seconds




------HipSTR Execution Summary------
Stutter model training succeeded for 0 out of 1 loci
Genotyping succeeded for 0 out of 0 loci

Approximate timing breakdown
 BAM seek time       = 0.000343 seconds
 Read filtering      = 4.20388 seconds
 SNP info extraction = 0.121632 seconds
 Stutter estimation  = 48.3759 seconds
 Genotyping          = 0 seconds
     Left alignment        = 0 seconds
     Haplotype generation  = 0 seconds
     Haplotype alignment   = 0 seconds
     Flank assembly        = 0 seconds
     Posterior computation = 0 seconds
     Alignment traceback   = 0 seconds
HipSTR execution finished: Total runtime = 55.866 sec
-----------------
```

**Comment by tfwillems** [comment]
Hi @nh13, 

Stutter model training fails when calls to train() in [*em_stutter_genotyper.cpp*](https://github.com/tfwillems/HipSTR/blob/0acd856a63419000d9db338d5c29ec1a45c2282d/src/em_stutter_genotyper.cpp#L171) return false 

This essentially means that the log-likelihood in the EM procedure isn't converging after 100 iterations. We currently consider it converged if the LL changes by less than 0.01 and by less than .1% between iterations. It may be that the first requirement is too stringent when you have many many reads, or perhaps something strange is going on.

I'd advise that you edit the first line in [*train()*](https://github.com/tfwillems/HipSTR/blob/0acd856a63419000d9db338d5c29ec1a45c2282d/src/em_stutter_genotyper.cpp#L171) such that *disp_stats= true* and monitor the messages that it prints out about the log-likelihoods. I'd be very curious to see what is output after you rerun your example and would be happy to adjust the convergence parameters if it makes sense.

Are you observing this issue frequently or is this just one pathological locus?

**Comment by tfwillems** [comment]
@nh13, Did this yield any insight?

**Comment by nh13** [comment]
@tfwillems I am still working on a few other issues, but this one is in my todo list.  I will definitely report back.

**Comment by tfwillems** [comment]
Closing this due to redundancy with Issue #46
