### ISSUE TITLE
Contigs missing in output VCF

### ISSUE THREAD

**Issue by nh13** [tfwillems/HipSTR#36]
Current behavior: only the contigs found in the input regions file is found in the output VCF file. 

Expected behavior: all contigs in the input FASTA file should be written to the output VCF.  Tools check that that contigs in the header match across VCFs (ex. GATK's ValidateVariants or Picard's GatherVcfs).  

The `write_contigs_to_vcf` function in https://github.com/tfwillems/HipSTR/blob/master/src/fasta_reader.cpp#L65-L71 should write ALL chromosomes, not just the one's passed in!

**Comment by nh13** [comment]
I also couldn't figure out why fastareader wants to have more than one index (why? are there multiple FASTAs? That seems wrong).

**Comment by tfwillems** [comment]
We used to allow a directory as input to --fasta instead of a single file. In that case, FastaReader would could handle a directory of indexed FASTA files instead of a single indexed FASTA file. But the behavior has since been deprecated
