### ISSUE TITLE
ERROR: BAM header mismatch issue

### ISSUE THREAD

**Issue by npatel22526** [tfwillems/HipSTR#39]
Hello Team, 

We have Bams from multiple cohort that we want to analyze with the HiPSTR. But, despite mapped to same human genome version (GRCh37) there are some difference in bams , such as one cohort is mapped with "hs37d5" chromosome and another with "NC_007605". Which seems to causing the issue and gives below error.

> 
> ERROR: BAM header mismatch issue. BAM headers for files File1.bam and File2.bam must have the same number of reference sequences
> Exiting...
> 

I can re-header the bams but that consumes both resources and huge storage space so before I implement that I wanted to make check weather there is a work around the issues. 

Thanks,
Nick

**Comment by tfwillems** [comment]
Hi Nick,

Are the discordant chromosomes the very last ones in the BAM header. If so, a simple workaround may be possible, but otherwise reheadering is likely your best bet. Happy to discuss more if this is the case

Best,
Thomas

**Comment by npatel22526** [comment]
Hello Thomas, 

Thanks for quick response. Yes, that is case here, discordant chromosomes  are the very last ones in the header. 

I have three different cohorts and last  2 chromosomes in each are
- cohortA : @SQ	SN:GL000225.1	LN:211173 and  @SQ	SN:GL000192.1	LN:547496
- cohortB : @SQ	SN:GL000192.1	LN:547496 and @SQ	SN:NC_007605	LN:171823
- cohortC : @SQ	SN:NC_007605	LN:171823 and @SQ	SN:hs37d5	LN:35477943

 
Best, 
Nick

**Comment by tfwillems** [comment]
Hi Nick,

There's currently no easy way to fix this from the command line and generally I wouldn't advocate for specific use case workarounds, but I can certainly understand that reheadering BAMs is not how you'd like to spend your hours. As a result, one option would be to go in and manually edit the `compare_bam_headers()` function in *bam_io.cpp*. I can't guarantee that this won't generate other issues, but I believe doing the following should work:

You'll need to change the first if statement in the function to:
`if (false && hdr_a->num_seqs() != hdr_b->num_seqs())` 

You'll also need to change the loop condition:
` for (int32_t i = 0; i < std::min(hdr_a->num_seqs(), hdr_b->num_seqs(); ++i){`

Finally, inside the loop, you should add if statements ignoring each of the 4 problematic sequences:
`if (hdr_a->ref_name(i).compare("GL000225.1") == 0) continue;`
`if (hdr_b->ref_name(i).compare("GL000225.1") == 0) continue;`
`...`

Let me know if that works

Best,
Thomas

**Comment by npatel22526** [comment]
Thanks a lot Thomas, 

Edited the _bam_io.cpp_ , recompiled and It worked like charm. I will do some quick sanity check on small set and update if there are any discrepancy in the output. 
Just small typo corrected below 

> for (int32_t i = 0; i < std::min(hdr_a->num_seqs(), hdr_b->num_seqs()**`)`**; ++i){

Thanks again , It saved me tons of hassle. 

Closing thread for now , do you think it's worth to incorporate in code , may be because the HiPSTR runs on chr1-22,X & Y only ? 

Best, 
Nick

**Comment by tfwillems** [comment]
Great Nick, happy to hear it did the trick. At this point, I'm not really in favor of incorporating these changes. I think it's better to be stringent about input data requirements to avoid any downstream issues

Best,
Thomas
