### ISSUE TITLE
Building using releases

### ISSUE THREAD

**Issue by cking-ha** [tfwillems/HipSTR#40]
It appears as if the process of building via releases is broken. Specifically, the Makefile uses git to determine the version, but the releases lack a functioning git repo to determine the version from.

**Comment by tfwillems** [comment]
Thanks for pointing this out. I hadn't noticed this issue as we recommend users install using `git clone` which will automatically construct the required git repo. However, as you pointed out, the git information isn't correctly populated when you use the github release link.

I've gone ahead and modified the Makefile such that this should no longer be an issue. I've constructed a new release (v0.5) that contains this fix and many others, so building using the release for **v0.5** should now work correctly.

Let me know if you have any issues
