### ISSUE TITLE
compiling htslib in release 0.5

### ISSUE THREAD

**Issue by shukwong** [tfwillems/HipSTR#42]
Hi, I am having trouble compiling htslib in release 0.5 and am wondering if you could help?

cd lib/htslib && make
make[1]: Entering directory `<local>/bin/HipSTR-0.5/lib/htslib'
gcc -g -Wall -O2 -I.  -c -o thread_pool.o thread_pool.c
thread_pool.c: In function ‘hts_tpool_init’:
thread_pool.c:676:5: warning: implicit declaration of function ‘pthread_mutexattr_settype’ [-Wimplicit-function-declaration]
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
     ^
thread_pool.c:676:38: error: ‘PTHREAD_MUTEX_RECURSIVE’ undeclared (first use in this function)
     pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
                                      ^
thread_pool.c:676:38: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [thread_pool.o] Error 1
make[1]: Leaving directory `<local>/bin/HipSTR-0.5/lib/htslib'
make: *** [lib/htslib/libhts.a] Error 2

**Comment by tfwillems** [comment]
Hi Wendy.

It looks like this is a known htslib issue that arises on old operating systems: https://github.com/samtools/htslib/issues/420

If you edit the Makefile in lib/htslib/Makefile and add -D_GNU_SOURCE to CFLAGS on line 36, does that solve your issue?

Best,
Thomas

**Comment by shukwong** [comment]
Hi Thomas,

Yes, that solved the problem and I am running HipSTR 0.5 now!

thanks!
Wendy
