### ISSUE TITLE
Compatibility with .bam from 10x Genomics

### ISSUE THREAD

**Issue by stephenwilliams22** [tfwillems/HipSTR#44]
Hi Thomas,
I'm trying to use .bams from 10x genomics with HipSTR. It looks like all reads are getting filtered out. for example when I run against your precompiled .bed file all the entries look like this: 

My code:

`
HipSTR   --bams 1M.bam,2M.bam,3M.bam,4M.bam
         --fasta hg19-2.2.0/fasta/genome.fa
         --regions hg19.hipstr_reference.bed
	 --min-reads=10
	 --output-phased-gls
	 --def-stutter-model
         --str-vcf str_calls.vcf.gz
`

Partial output of HipSTR:

`Processing region chrX 146993567 146993629
715 reads overlapped region, of which
	459 were hard clipped
	2 had an 'N' base call
	0 had low base quality scores
	0 did not span the STR
	33 did not have a unique mapping
	221 did not have a mate pair
	0 PASSED ALL FILTERS
Found 0 fully paired reads and 0 unpaired reads for downstream analyses
Removed 0 sets of PCR duplicate reads
Phased SNPs add info for 0 out of 0 reads and 0 out of 0 samples
Skipping locus with too few reads: TOTAL=0, MIN=10

------HipSTR Execution Summary------
Skipped 10 loci with too few reads for stutter model model training or genotyping.
	 If this comprises a sizeable portion of your loci, see the --min-reads command line option
Genotyping succeeded for 0 out of 0 loci

Approximate timing breakdown
 BAM seek time       = 0.14 seconds
 Read filtering      = 0.1 seconds
 SNP info extraction = 0 seconds
 Stutter estimation  = 0 seconds
 Genotyping          = 0 seconds
	 Left alignment        = 0 seconds
	 Haplotype generation  = 0 seconds
	 Haplotype alignment   = 0 seconds
	 Flank assembly        = 0 seconds
	 Posterior computation = 0 seconds
	 Alignment traceback   = 0 seconds
HipSTR execution finished: Total runtime = 9.04 sec
-----------------`

Here is an example entry from one of the .bam files:

`A00215:26:H3CC3DMXX:2:2156:32732:6574	147	chr1	9989	36	84S67M	=	10008	-48	CCCCCCCCCCCCCCCCCCTTATAAGCACACGCCGACCACCGAGATCTACACTCTTTCCCTAAACGACTCTCTTCCGATCTTTAGGTGTCAGTCCCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCT	FFFFFF--FFFFF-F--------------8--F--F-FFF-8---88FF-FFFFFFF8-FF--FF---FFFFFFFFFF--FFFF-FFFFFF--FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	QT:Z:FFFFFFFF	BC:Z:TGCCGTGG	QX:Z:FFFFFFFFFFFFFFFF	AM:A:0	XM:A:1	RX:Z:TTAGGTGTCAGGCCCA	AS:f:-95.5	XS:f:-97.5	BX:Z:TTAGGTGTCAGGCCCA-1	XT:i:0	OM:i:0	RG:Z:DBS_1M:LibraryNotSpecified:1:unknown_fc:0`

Do you think that this .bam should/could be compatible?  Any assistance would be greatly appreciated.

**Comment by tfwillems** [comment]
Hi Stephen,

Sorry about this issue. I believe this is due to the AS/XS tags that LongRanger reports. In general, HipSTR assumes these tags, if present, are similar to the tags reported by BWA-MEM (i.e. the scores for the optimal and suboptimal alignment). It then uses them to ensure that paired alignments map sufficiently uniquely to the current STR and should be analyzed during genotyping. In LongRanger's case, it's XS and AS tags seem to be very different, as it returns negative floats instead of positive integers. 

Is there some documentation about what these values represent? If so, I can adapt HipSTR to potentially use this information. If not, I'm sure I can easily work around this issue and just ignore these tags when 10x-bams are being used as input.

Previously I built a special **--10x-bams** option into HipSTR to leverage the haplotype tags (HP) reported by LongRanger. The idea is that we could use this information for phasing in the genotyping process, analogous to the input for --snp-vcf for regular BAMs. I never made this option publicly visible, as I haven't debugged it thorough, but it may be useful once we fix the above issue. I also think whichever fix we devise can easily be added to be enabled with this option.

Best,
Thomas

**Comment by stephenwilliams22** [comment]
Hi Thomas,
AS - Alignment score including mate and pairing info, not including molecule (shared barcode) info.
XS - Second best alignment score including mate and pairing info, not including molecule info. Because this does not include molecule info, XS may be greater than AS.

I just found out that we are actually doing some internal development to see what the best way to utilize these tags is and it would be awesome if HipSTR could take advantage of them. It would be really great to take advantage of the phasing that the 10x bams include. 

In the short term, if we could just ignore the tags it would be awesome. As soon as we debug these Tags internally I'll circle back so we can take full advantage of the data. 

Thanks again,
Stephen

**Comment by tfwillems** [comment]
Hi Stephen,

Thanks for the info. I'll develop a workaround and get back to you early next week at the latest.

Just out of curiosity, wny idea why the AS and XS values are negative? Are they potentially log-likelihoods?

Best,
Thomas

**Comment by stephenwilliams22** [comment]
Thanks Thomas. For the meantime I removed these fields from my .bams. Do you see any major downside to this? I'll get back to you ASAP about the negative values.

Stephen

**Comment by tfwillems** [comment]
Hi Stephen,

Until I understand how they are related to the XS/AS tags reported by BWA-MEM, I would just ignore them anyways, so this approach is as good as my temporary fix.

The downside of not having these tags is that HipSTR can't filter out reads that are potentially misaligned to the locus. For a given STR, this can of course be a big issue, as many repeats are highly duplicated across the genome. But if LongRanger does a good job masking these, this may not be much of an issue. Alternatively, if there are other flags that might be informative of such instances, we could incorporate them as well, so let me know if any come to mind

Best,
Thomas

**Comment by stephenwilliams22** [comment]
Hi Thomas,
Thanks for all the helpful info here.

The one thing that would be really nice to use would be the phasing information in the HP tag. You might be able to take advantage of the BX (corrected) barcode tag as well as this will indicate the relationship between reads on a given molecule and help to distinguish haplotypes as well. Maybe color coding reads associated with each haplotype, no color for those not associated with a haplotype, on the visual output would be a good way to do this.

As for the tags I'll work on getting you a clear explanation on how these could best be utilized. 

Thanks again!

Stephen

**Comment by stephenwilliams22** [comment]
Hi Thomas,
Following up on the XS/AS tag. Here's the code for how the calculation is performed. A perfect score starts at 0 and then gets penalized down from there.  So it can be interpreted as a log-likelihood.

https://github.com/10XGenomics/lariat/blob/master/go/src/inference/lariat.go#L590

**Comment by stephenwilliams22** [comment]
Hi Thomas,
Just wanted to let you know that HipSTR worked great when I removed the tags. Is there any progress on utilization of the linked-read data?

Thanks,

Stephen

**Comment by tfwillems** [comment]
Hi Stephen,

Sorry I haven't been able to dig into this in greater detail, as I've been busy with work-related commitments. But most of the functionality should already be there in terms of using the **HP** tag information. The **--10x-bams** option, although not listed in the help message, is actually already present, so you merely need to run HipSTR with this extra option (and no argument). It'll then use the *HP* values, when present, to assign reads to either haplotype 1 or haplotype 2, information which is then automatically used in the downstream genotyping process. For the specifics about this, check out  the function [process_10x_reads](https://github.com/tfwillems/HipSTR/blob/master/src/snp_bam_processor.cpp).

I'd recommend running HipSTR with and without the **--10x-bams** option and see how the results compare. It'd be great if you could let me know what you find and whether this information actually improves performance at all.

In terms of the *BX* tag, how would you suggest using that information?

Best,
Thomas

**Comment by stephenwilliams22** [comment]
Hi Thomas,
I wanted to reach back out about how to best utilize some of the extra information in the 10x Genomics bam files. The --10x-bams option worked nicely. I have some ideas that I think might help down the road. Do you think you'd have some time to chat about this? Maybe best if we do this outside of github? Didn't want to clog up this feed with trivial info. My email is stephen.williams[at]10xgenomics.com if you want to set something up. 

Thanks,

Stephen

**Comment by tfwillems** [comment]
Hi @stephenwilliams22 ,

Thanks for reporting back! I'll email you to set something up

Best,
Thomas
