### ISSUE TITLE
Error filtering diploid STR calls: filter_vcf.py

### ISSUE THREAD

**Issue by SteveSemick** [tfwillems/HipSTR#51]
Dear HipSTR authors,

I recently ran into this error (below) while filtering the output from HipSTR. Oddly, I did not encounter this error when running the suggested filtering code for haploid chromosomes. Please let me know if you have seen this error before or have any insight.

Thank you for your time.

Best,
Steve

The call:
``` 
python ${HIPSTR}filter_vcf.py --vcf concat_diploid_calls_sorted.vcf.gz --min-call-qual 0.9 --max-call-flank-indel 0.15 --max-call-stutter 0.15 | bgzip -c > concat_diploid_calls_filt.vcf.gz 
```

The error:
``` python ${HIPSTR}filter_vcf.py --vcf con                                                                          cat_diploid_calls_sorted.vcf.gz --min-call-qual 0.9 --max-call-flank-indel 0.15 --max-call-stutter                                                                           0.15 | bgzip -c > concat_diploid_calls_filt.vcf.gz
Traceback (most recent call last):
  File "/users/ssemick/HipSTR/scripts/filter_vcf.py", line 216, in <module>
    main()
  File "/users/ssemick/HipSTR/scripts/filter_vcf.py", line 120, in main
    filter_reason = filter_call(sample, args)
  File "/users/ssemick/HipSTR/scripts/filter_vcf.py", line 11, in filter_call
    if sample['DP'] < filters.DEPTH:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

To prepare the input file, I had run the following code:
```vcftools --gzvcf concat.vcf.gz --recode --recode-INFO-all --chr chr1 --chr chr2 --chr chr3 --chr chr4 --chr chr5 --chr chr6 --chr chr7 --chr chr8 --chr chr9 --chr chr10 --chr chr11 --chr chr12 --chr chr13 --chr chr14 --chr chr15 --chr chr16 --chr chr17 --chr chr18 --chr chr19 --chr chr20 --chr chr21 --chr chr22  -c | bgzip -c > concat_diploid_calls.vcf.gz
vcf-sort -c concat_diploid_calls.vcf.gz | bgzip -c > concat_diploid_calls_sorted.vcf.gz
tabix -p vcf concat_diploid_calls_sorted.vcf.gz
```

**Comment by tfwillems** [comment]
Hi Steve, 

Sorry about this issue and thanks for the detailed report. Can you verify that you're using the most recent version of HipSTR (v0.6.1)?

 If so, it'd be great if you could add a line to *filter_vcf.py* at line 154. If you could add the statement 
`print(sample)` 
on the line right before 
`if sample['GT'] is None or sample['GT'] == "./." or sample['GT'] == ".":`
the last printed line will tell us precisely why it's crashing.

Thanks!

Best,
Thomas

**Comment by SteveSemick** [comment]
I had been using an installation from May 31st 2017. 

I installed the latest version and ran the same code. The problem appears to be solved. Thanks for your help Thomas.

Best,
Steve

**Comment by SteveSemick** [comment]
I had been using an installation from May 31st 2017.

I installed the latest version and ran the same code. The problem appears to be solved. Thanks for your help Thomas.

Best,
Steve
