### ISSUE TITLE
 AMEL bed area not in the provided bed file

### ISSUE THREAD

**Issue by zhangyafeng1** [tfwillems/HipSTR#73]
hello:
I am a newbie, the problem may seem simple
Why are there no bed area for the AMEL genome on the X and Y chromosomes in the provided bed file?

Thank you very much!

**Comment by tfwillems** [comment]
Hi @zhangyafeng1 ,

Since this marker is present on both the X and Y chromosomes, aligners may have a hard time uniquely mapping to one vs. the other. You can certainly add an entry for it to the BED files if you’re interested in seeing how it performs

Best,
Thomas
