### ISSUE TITLE
No output for a specific locus

### ISSUE THREAD

**Issue by liuqianhn** [tfwillems/HipSTR#74]
Hi, I used your tools to detect STR for several specific loci. But I found that there is no output for some of them. May I know what that means? For example, I give 10 loci to HipSTR, but only 7 loci are in the output file. What happens to the missed 3 loci? Thank you.

**Comment by tfwillems** [comment]
Hi @liuqianhn ,

HipSTR generally tries to genotype every STR in your BED file, but if something problematic occurs during the genotyping process of a locus, it will skip it and report the reason for doing so in the log file. This approach avoids reporting calls for error prone loci. I’d recommend rerunning HipSTr with  the log option enabled and inspecting the corresponding log file. There may be a few options you can tweak to generate results for the other 3 loci
