### ISSUE TITLE
Working with HipSTR

### ISSUE THREAD

**Issue by jayala** [tfwillems/HipSTR#84]
Hello Thomas!
How are you?
 
We just wanted to let you know that the paper we worked on with HipSTR was published in FSI journal, we included it as an attachment. In it you’ll find a comparison between three bioinformatic softwares to calculate STRs genotypes from NGS data (HipSTR, STRait Razor and toaSTR).
 
Working with HipSTR was very straightforward and we were able to work with large databases with no difficulties. We found some areas where HipSTR could be improved and some errors:
1.	We found nomenclature errors in some markers, (actually they are the results of mathematical calculations, as we explain in the paper);
2.	Something reviewers claimed the most was; it does not differentiate “isoaleles”; those that have the same length but different sequence.
3.	It is not easy to use without previous bioinformatics experience;
 
We would love to work, with your authorization of course, and together if possible in developing an UI for HipSTR to simplify the uploading of samples, processing, allele calculations, etc.
 
Also is there any chance of showing as results these isoaleles? toaSTR already makes that differentiation if you want to test. For example, as a result it shows allele 15 and 15b (two alleles with 11 repetitions but with different sequence). Below is the image of the result:
 
 
![image](https://user-images.githubusercontent.com/1461486/164815780-9cef3a04-8c9b-4344-b909-461f9523d7e0.png)

 
We believe that with these changes HipSTR could be widely adopted and we would love to help with this.
 
Regards,
Jesús and Tamara.

**Comment by aubreybailey** [comment]
It would help if you provided an un-paywalled / open-access version of your article.

**Comment by jayala** [comment]
Hello Aubrey, thanks for the reply. Sure, here is a public link to the article: https://drive.google.com/file/d/1kGWm9Hpwqzqq7shSI0kOMCNDF7lpFWNl/view?usp=sharing
